<!DOCTYPE html> <html lang="en" xmlns="http://www.w3.org/1999/xhtml"> <head> <meta charset="utf-8" /> <title>Internal Server Error</title> <style> body { font-family: 'Segoe UI', Tahoma, Arial, Helvetica, sans-serif; font-size: .813em; color: #222; background-color: #fff; } h1, h2, h3, h4, h5 { /*font-family: 'Segoe UI',Tahoma,Arial,Helvetica,sans-serif;*/ font-weight: 100; } h1 { color: #44525e; margin: 15px 0 15px 0; } h2 { margin: 10px 5px 0 0; } h3 { color: #363636; margin: 5px 5px 0 0; } code { font-family: Consolas, "Courier New", courier, monospace; } body .titleerror { padding: 3px 3px 6px 3px; display: block; font-size: 1.5em; font-weight: 100; } body .location { margin: 3px 0 10px 30px; } #header { font-size: 18px; padding: 15px 0; border-top: 1px #ddd solid; border-bottom: 1px #ddd solid; margin-bottom: 0; } #header li { display: inline; margin: 5px; padding: 5px; color: #a0a0a0; cursor: pointer; } #header .selected { background: #44c5f2; color: #fff; } #stackpage ul { list-style: none; padding-left: 0; margin: 0; /*border-bottom: 1px #ddd solid;*/ } #stackpage .details { font-size: 1.2em; padding: 3px; color: #000; } #stackpage .stackerror { padding: 5px; border-bottom: 1px #ddd solid; } #stackpage .frame { padding: 0; margin: 0 0 0 30px; } #stackpage .frame h3 { padding: 2px; margin: 0; } #stackpage .source { padding: 0 0 0 30px; } #stackpage .source ol li { font-family: Consolas, "Courier New", courier, monospace; white-space: pre; background-color: #fbfbfb; } #stackpage .frame .source .highlight li span { color: #FF0000; } #stackpage .source ol.collapsible li { color: #888; } #stackpage .source ol.collapsible li span { color: #606060; } .page table { border-collapse: separate; border-spacing: 0; margin: 0 0 20px; } .page th { vertical-align: bottom; padding: 10px 5px 5px 5px; font-weight: 400; color: #a0a0a0; text-align: left; } .page td { padding: 3px 10px; } .page th, .page td { border-right: 1px #ddd solid; border-bottom: 1px #ddd solid; border-left: 1px transparent solid; border-top: 1px transparent solid; box-sizing: border-box; } .page th:last-child, .page td:last-child { border-right: 1px transparent solid; } .page .length { text-align: right; } a { color: #1ba1e2; text-decoration: none; } a:hover { color: #13709e; text-decoration: underline; } .showRawException { cursor: pointer; color: #44c5f2; background-color: transparent; font-size: 1.2em; text-align: left; text-decoration: none; display: inline-block; border: 0; padding: 0; } .rawExceptionStackTrace { font-size: 1.2em; } .rawExceptionBlock { border-top: 1px #ddd solid; border-bottom: 1px #ddd solid; } .showRawExceptionContainer { margin-top: 10px; margin-bottom: 10px; } .expandCollapseButton { cursor: pointer; float: left; height: 16px; width: 16px; font-size: 10px; position: absolute; left: 10px; background-color: #eee; padding: 0; border: 0; margin: 0; } </style> </head> <body> <h1>An unhandled exception occurred while processing the request.</h1> <div class="titleerror">ExtendedSocketException: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond 169.38.103.42:578</div> <p class="location">System.Net.Sockets.Socket.EndConnect(IAsyncResult asyncResult)</p> <div class="titleerror">SmtpException: Failure sending mail.</div> <p class="location">overtime_service.Controllers.AccountController.Register(RegisterViewModel model) in <code title="C:\Users\amnat\source\dotnetcore\overTime\overtime-service\Controllers\AccountController.cs">AccountController.cs</code>, line 55</p> <ul id="header"> <li id="stack" tabindex="1" class="selected"> Stack </li> <li id="query" tabindex="2"> Query </li> <li id="cookies" tabindex="3"> Cookies </li> <li id="headers" tabindex="4"> Headers </li> </ul> <div id="stackpage" class="page"> <ul> <li> <h2 class="stackerror">ExtendedSocketException: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond 169.38.103.42:578</h2> <ul> <li class="frame" id="frame1"> <h3>System.Net.Sockets.Socket.EndConnect(IAsyncResult asyncResult)</h3> </li> <li class="frame" id="frame2"> <h3>System.Net.Sockets.Socket.DoMultipleAddressConnectCallback(object result, MultipleAddressConnectAsyncResult context)</h3> </li> <li class="frame" id="frame3"> <h3>System.Net.Sockets.Socket.DoMultipleAddressConnectCallback(object result, MultipleAddressConnectAsyncResult context)</h3> </li> <li class="frame" id="frame4"> <h3>System.Net.Sockets.Socket.MultipleAddressConnectCallback(IAsyncResult result)</h3> </li> <li class="frame" id="frame5"> <h3>System.Net.Sockets.Socket.EndConnect(IAsyncResult asyncResult)</h3> </li> <li class="frame" id="frame6"> <h3>System.Net.Sockets.TcpClient.EndConnect(IAsyncResult asyncResult)</h3> </li> <li class="frame" id="frame7"> <h3>System.Net.Mail.SmtpConnection&#x2B;ConnectAndHandshakeAsyncResult.InitializeConnectionCallback(IAsyncResult result)</h3> </li> <li class="frame" id="frame8"> <h3>System.Net.Mail.SmtpConnection&#x2B;ConnectAndHandshakeAsyncResult.End(IAsyncResult result)</h3> </li> <li class="frame" id="frame9"> <h3>System.Net.Mail.SmtpTransport.EndGetConnection(IAsyncResult result)</h3> </li> <li class="frame" id="frame10"> <h3>System.Net.Mail.SmtpClient.ConnectCallback(IAsyncResult result)</h3> </li> </ul> </li> <li> <br/> <div class="rawExceptionBlock"> <div class="showRawExceptionContainer"> <button class="showRawException" data-exceptionDetailId="exceptionDetail1">Show raw exception details</button> </div> <div id="exceptionDetail1" class="rawExceptionDetails"> <pre class="rawExceptionStackTrace">System.Net.Internals.SocketExceptionFactory&#x2B;ExtendedSocketException (10060): A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond 169.38.103.42:578&#xD;&#xA; at System.Net.Sockets.Socket.EndConnect(IAsyncResult asyncResult)&#xD;&#xA; at System.Net.Sockets.Socket.DoMultipleAddressConnectCallback(Object result, MultipleAddressConnectAsyncResult context)&#xD;&#xA;--- End of stack trace from previous location where exception was thrown ---&#xD;&#xA; at System.Net.Sockets.Socket.DoMultipleAddressConnectCallback(Object result, MultipleAddressConnectAsyncResult context)&#xD;&#xA; at System.Net.Sockets.Socket.MultipleAddressConnectCallback(IAsyncResult result)&#xD;&#xA;--- End of stack trace from previous location where exception was thrown ---&#xD;&#xA; at System.Net.Sockets.Socket.EndConnect(IAsyncResult asyncResult)&#xD;&#xA; at System.Net.Sockets.TcpClient.EndConnect(IAsyncResult asyncResult)&#xD;&#xA; at System.Net.Mail.SmtpConnection.ConnectAndHandshakeAsyncResult.InitializeConnectionCallback(IAsyncResult result)&#xD;&#xA;--- End of stack trace from previous location where exception was thrown ---&#xD;&#xA; at System.Net.Mail.SmtpConnection.ConnectAndHandshakeAsyncResult.End(IAsyncResult result)&#xD;&#xA; at System.Net.Mail.SmtpTransport.EndGetConnection(IAsyncResult result)&#xD;&#xA; at System.Net.Mail.SmtpClient.ConnectCallback(IAsyncResult result)</pre> </div> </div> </li> <li> <h2 class="stackerror">SmtpException: Failure sending mail.</h2> <ul> <li class="frame" id="frame11"> <h3>overtime_service.Controllers.AccountController.Register(RegisterViewModel model) in <code title="C:\Users\amnat\source\dotnetcore\overTime\overtime-service\Controllers\AccountController.cs">AccountController.cs</code></h3> <button class="expandCollapseButton" data-frameId="frame11">+</button> <div class="source"> <ol start="49" class="collapsible"> <li><span> return BadRequest(registerResult.Errors);</span></li> <li><span></span></li> <li><span> await _userManager.AddToRoleAsync(user, &quot;Customer&quot;);</span></li> <li><span> var vcode = await _userManager.GenerateEmailConfirmationTokenAsync(user);</span></li> <li><span></span></li> <li><span> var callbackUrl = Url.Action(&quot;ConfirmEmail&quot;, &quot;Account&quot;, new { userId = user.Id, code = vcode }, protocol: Request.Scheme);</span></li> </ol> <ol start="55" class="highlight"> <li><span> await _emailSender.SendEmailAsync(model.Email, &quot;Confirm your account&quot;,</span></li> </ol> <ol start='56' class="collapsible"> <li><span> &quot;Please confirm your account by clicking this link: &lt;a href=\&quot;&quot; &#x2B; callbackUrl &#x2B; &quot;\&quot;&gt;link&lt;/a&gt;&quot;);</span></li> <li><span> //await _signInManager.SignInAsync(user, isPersistent: false);</span></li> <li><span> //return RedirectToAction(nameof(HomeController.Index), &quot;Home&quot;);</span></li> <li><span></span></li> <li><span> return Ok(user);</span></li> <li><span> }</span></li> </ol> </div> </li> <li class="frame" id="frame12"> <h3>Microsoft.AspNetCore.Mvc.Internal.ActionMethodExecutor&#x2B;TaskOfIActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, object controller, object[] arguments)</h3> </li> <li class="frame" id="frame13"> <h3>System.Threading.Tasks.ValueTask&lt;TResult&gt;.get_Result()</h3> </li> <li class="frame" id="frame14"> <h3>Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeActionMethodAsync()</h3> </li> <li class="frame" id="frame15"> <h3>Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeNextActionFilterAsync()</h3> </li> <li class="frame" id="frame16"> <h3>Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Rethrow(ActionExecutedContext context)</h3> </li> <li class="frame" id="frame17"> <h3>Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Next(ref State next, ref Scope scope, ref object state, ref bool isCompleted)</h3> </li> <li class="frame" id="frame18"> <h3>Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeInnerFilterAsync()</h3> </li> <li class="frame" id="frame19"> <h3>Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeNextResourceFilter()</h3> </li> <li class="frame" id="frame20"> <h3>Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Rethrow(ResourceExecutedContext context)</h3> </li> <li class="frame" id="frame21"> <h3>Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Next(ref State next, ref Scope scope, ref object state, ref bool isCompleted)</h3> </li> <li class="frame" id="frame22"> <h3>Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeFilterPipelineAsync()</h3> </li> <li class="frame" id="frame23"> <h3>Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeAsync()</h3> </li> <li class="frame" id="frame24"> <h3>Microsoft.AspNetCore.Routing.EndpointMiddleware.Invoke(HttpContext httpContext)</h3> </li> <li class="frame" id="frame25"> <h3>Microsoft.AspNetCore.Routing.EndpointRoutingMiddleware.Invoke(HttpContext httpContext)</h3> </li> <li class="frame" id="frame26"> <h3>Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)</h3> </li> <li class="frame" id="frame27"> <h3>Microsoft.AspNetCore.Cors.Infrastructure.CorsMiddleware.InvokeCore(HttpContext context)</h3> </li> <li class="frame" id="frame28"> <h3>Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)</h3> </li> </ul> </li> <li> <br/> <div class="rawExceptionBlock"> <div class="showRawExceptionContainer"> <button class="showRawException" data-exceptionDetailId="exceptionDetail2">Show raw exception details</button> </div> <div id="exceptionDetail2" class="rawExceptionDetails"> <pre class="rawExceptionStackTrace">System.Net.Mail.SmtpException: Failure sending mail. ---&gt; System.Net.Internals.SocketExceptionFactory&#x2B;ExtendedSocketException: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond 169.38.103.42:578&#xD;&#xA; at System.Net.Sockets.Socket.EndConnect(IAsyncResult asyncResult)&#xD;&#xA; at System.Net.Sockets.Socket.DoMultipleAddressConnectCallback(Object result, MultipleAddressConnectAsyncResult context)&#xD;&#xA;--- End of stack trace from previous location where exception was thrown ---&#xD;&#xA; at System.Net.Sockets.Socket.DoMultipleAddressConnectCallback(Object result, MultipleAddressConnectAsyncResult context)&#xD;&#xA; at System.Net.Sockets.Socket.MultipleAddressConnectCallback(IAsyncResult result)&#xD;&#xA;--- End of stack trace from previous location where exception was thrown ---&#xD;&#xA; at System.Net.Sockets.Socket.EndConnect(IAsyncResult asyncResult)&#xD;&#xA; at System.Net.Sockets.TcpClient.EndConnect(IAsyncResult asyncResult)&#xD;&#xA; at System.Net.Mail.SmtpConnection.ConnectAndHandshakeAsyncResult.InitializeConnectionCallback(IAsyncResult result)&#xD;&#xA;--- End of stack trace from previous location where exception was thrown ---&#xD;&#xA; at System.Net.Mail.SmtpConnection.ConnectAndHandshakeAsyncResult.End(IAsyncResult result)&#xD;&#xA; at System.Net.Mail.SmtpTransport.EndGetConnection(IAsyncResult result)&#xD;&#xA; at System.Net.Mail.SmtpClient.ConnectCallback(IAsyncResult result)&#xD;&#xA; --- End of inner exception stack trace ---&#xD;&#xA; at overtime_service.Controllers.AccountController.Register(RegisterViewModel model) in C:\Users\amnat\source\dotnetcore\overTime\overtime-service\Controllers\AccountController.cs:line 55&#xD;&#xA; at Microsoft.AspNetCore.Mvc.Internal.ActionMethodExecutor.TaskOfIActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)&#xD;&#xA; at System.Threading.Tasks.ValueTask`1.get_Result()&#xD;&#xA; at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeActionMethodAsync()&#xD;&#xA; at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeNextActionFilterAsync()&#xD;&#xA; at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Rethrow(ActionExecutedContext context)&#xD;&#xA; at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Next(State&amp; next, Scope&amp; scope, Object&amp; state, Boolean&amp; isCompleted)&#xD;&#xA; at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeInnerFilterAsync()&#xD;&#xA; at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeNextResourceFilter()&#xD;&#xA; at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Rethrow(ResourceExecutedContext context)&#xD;&#xA; at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Next(State&amp; next, Scope&amp; scope, Object&amp; state, Boolean&amp; isCompleted)&#xD;&#xA; at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeFilterPipelineAsync()&#xD;&#xA; at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeAsync()&#xD;&#xA; at Microsoft.AspNetCore.Routing.EndpointMiddleware.Invoke(HttpContext httpContext)&#xD;&#xA; at Microsoft.AspNetCore.Routing.EndpointRoutingMiddleware.Invoke(HttpContext httpContext)&#xD;&#xA; at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)&#xD;&#xA; at Microsoft.AspNetCore.Cors.Infrastructure.CorsMiddleware.InvokeCore(HttpContext context)&#xD;&#xA; at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)</pre> </div> </div> </li> </ul> </div> <div id="querypage" class="page"> <p>No QueryString data.</p> </div> <div id="cookiespage" class="page"> <p>No cookie data.</p> </div> <div id="headerspage" class="page"> <table> <thead> <tr> <th>Variable</th> <th>Value</th> </tr> </thead> <tbody> <tr> <td>Accept</td> <td>application/json, text/plain, */*</td> </tr> <tr> <td>Accept-Encoding</td> <td>gzip, deflate, br</td> </tr> <tr> <td>Accept-Language</td> <td>en-US,en;q=0.9,th;q=0.8</td> </tr> <tr> <td>Connection</td> <td>keep-alive</td> </tr> <tr> <td>Content-Length</td> <td>105</td> </tr> <tr> <td>Content-Type</td> <td>application/json;charset=UTF-8</td> </tr> <tr> <td>Host</td> <td>localhost:5001</td> </tr> <tr> <td>Origin</td> <td>http://localhost:8080</td> </tr> <tr> <td>Referer</td> <td>http://localhost:8080/register</td> </tr> <tr> <td>Sec-Fetch-Mode</td> <td>cors</td> </tr> <tr> <td>Sec-Fetch-Site</td> <td>cross-site</td> </tr> <tr> <td>User-Agent</td> <td>Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/78.0.3904.70 Safari/537.36</td> </tr> </tbody> </table> </div> <script> //<!-- (function (window, undefined) { "use strict"; function ns(selector, element) { return new NodeCollection(selector, element); } function NodeCollection(selector, element) { this.items = []; element = element || window.document; var nodeList; if (typeof (selector) === "string") { nodeList = element.querySelectorAll(selector); for (var i = 0, l = nodeList.length; i < l; i++) { this.items.push(nodeList.item(i)); } } } NodeCollection.prototype = { each: function (callback) { for (var i = 0, l = this.items.length; i < l; i++) { callback(this.items[i], i); } return this; }, children: function (selector) { var children = []; this.each(function (el) { children = children.concat(ns(selector, el).items); }); return ns(children); }, hide: function () { this.each(function (el) { el.style.display = "none"; }); return this; }, toggle: function () { this.each(function (el) { el.style.display = el.style.display === "none" ? "" : "none"; }); return this; }, show: function () { this.each(function (el) { el.style.display = ""; }); return this; }, addClass: function (className) { this.each(function (el) { var existingClassName = el.className, classNames; if (!existingClassName) { el.className = className; } else { classNames = existingClassName.split(" "); if (classNames.indexOf(className) < 0) { el.className = existingClassName + " " + className; } } }); return this; }, removeClass: function (className) { this.each(function (el) { var existingClassName = el.className, classNames, index; if (existingClassName === className) { el.className = ""; } else if (existingClassName) { classNames = existingClassName.split(" "); index = classNames.indexOf(className); if (index > 0) { classNames.splice(index, 1); el.className = classNames.join(" "); } } }); return this; }, attr: function (name) { if (this.items.length === 0) { return null; } return this.items[0].getAttribute(name); }, on: function (eventName, handler) { this.each(function (el, idx) { var callback = function (e) { e = e || window.event; if (!e.which && e.keyCode) { e.which = e.keyCode; // Normalize IE8 key events } handler.apply(el, [e]); }; if (el.addEventListener) { // DOM Events el.addEventListener(eventName, callback, false); } else if (el.attachEvent) { // IE8 events el.attachEvent("on" + eventName, callback); } else { el["on" + type] = callback; } }); return this; }, click: function (handler) { return this.on("click", handler); }, keypress: function (handler) { return this.on("keypress", handler); } }; function frame(el) { ns(".source .collapsible", el).toggle(); } function expandCollapseButton(el) { var frameId = el.getAttribute("data-frameId"); frame(document.getElementById(frameId)); if (el.innerText === "+") { el.innerText = "-"; } else { el.innerText = "+"; } } function tab(el) { var unselected = ns("#header .selected").removeClass("selected").attr("id"); var selected = ns("#" + el.id).addClass("selected").attr("id"); ns("#" + unselected + "page").hide(); ns("#" + selected + "page").show(); } ns(".rawExceptionDetails").hide(); ns(".collapsible").hide(); ns(".page").hide(); ns("#stackpage").show(); ns(".expandCollapseButton") .click(function () { expandCollapseButton(this); }) .keypress(function (e) { if (e.which === 13) { expandCollapseButton(this); } }); ns("#header li") .click(function () { tab(this); }) .keypress(function (e) { if (e.which === 13) { tab(this); } }); ns(".showRawException") .click(function () { var exceptionDetailId = this.getAttribute("data-exceptionDetailId"); ns("#" + exceptionDetailId).toggle(); }); })(window); //--> </script> </body> </html>
